apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-dataview
  labels:
    app: {{.Release.Name}}-dataview
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.type}}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8111
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-dataview