# Default values for dataviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

component:
  # Specifies whether a service account should be created
  type: dataviewer